import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Advent of Code 2022</h1>

        <p className={styles.description}>Get started by picking a day.</p>

        <div className={styles.grid}>
          <a href="/1" className={styles.card}>
            <h2>Day 1 &rarr;</h2>
            <p>
              Find the elf carrying the most calories. How many calories is that
              elf carrying?
            </p>
          </a>

          <a href="/2" className={styles.card}>
            <h2>Day 2 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/3" className={styles.card}>
            <h2>Day 3 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/4" className={styles.card}>
            <h2>Day 4 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/5" className={styles.card}>
            <h2>Day 5 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/6" className={styles.card}>
            <h2>Day 6 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/7" className={styles.card}>
            <h2>Day 7 &rarr;</h2>
            <p>description coming</p>
          </a>

          <a href="/8" className={styles.card}>
            <h2>Day 8 &rarr;</h2>
            <p>description coming</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
